apiVersion: apps/v1
kind: Deployment
metadata:
  name: boostsync-deployment
  labels:
    app: boostsync
spec:
  replicas: 1
  selector:
    matchLabels:
      app: boostsync
  template:
    metadata:
      labels:
        app: boostsync
    spec:
      containers:
      - name: boostsync
        image: ddangoh/boostsync:v0.1
        ports:
        - containerPort: 12345
