apiVersion: v1
kind: Service
metadata:
  name: boostsync-service
spec:
  type: NodePort
  selector:
    app: boostsync
  ports:
    - protocol: UDP
      port: 12345
      targetPort: 12345
      nodePort: 30000
