apiVersion: apps/v1
kind: Deployment
metadata:
  name: boostsync-deployment
  labels:
    app: boostsync
spec:
  replicas: 2
  selector:
    matchLabels:
      app: boostsync
  template:
    metadata:
      labels:
        app: boostsync
    spec:
      containers:
      - name: boostsync
        image: ddangoh/boostsync:v0.2
        ports:
        - containerPort: 12345
